#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
	;}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner" \
	findnh="find ~ -name" \
	findnr="sudo find / -name"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \

alias \
	trti="transmission-remote -t $1 -i" \
	trl="transmission-remote -l" \

pve() {
    case "$1" in
        d) deactivate; return ;;
        c)
            mkdir -p "$2" && python -m venv "$2" && cd "$2" && source ./bin/activate
            [ "$3" = "jnb" ] && {
                pip list --outdated | grep pip  > /dev/null 2>&1 && pip install --upgrade pip
                pip show notebook > /dev/null 2>&1 || pip install notebook
                jupyter notebook
            }
            return
            ;;
        ddd)
            printf "Deactivating and permanently deleting the directoy. (y/n) " && read -r CHOICE
            case "$CHOICE" in
                [yY]|[yY][eE][sS])
                    printf "Are you sure? (y/n) " && read -r CHOICE2
                    case "$CHOICE2" in
                        [yY]|[yY][eE][sS])
                            WKDIR=$(pwd)
                            deactivate
                            cd "$(dirname "$WKDIR")" && rm -rf "$(basename "$WKDIR")"
                            ;;
                    esac
                    ;;
            esac
            return
            ;;
        "") : ;;
    esac

    if [ -d "$1" ] && [ -f "$1/bin/activate" ]; then
        cd "$1" && source bin/activate
        [ "$2" = "jnb" ] && jupyter notebook
    else
        [ -n "$1" ] && echo "Error: '$1' is not a valid virtual environment directory."
    fi
}
