#!/bin/sh

sudo qemu-system-x86_64 \
    -name opensuse-tw \
    -pidfile $HOME/qemuvirt/runpid/qemu-opensuse-tw.pid \
    -enable-kvm \
    -cpu host \
    -smp 2 \
    -m 4096 \
    -drive file=$HOME/qemuvirt/images/opensuse-tw.qcow2,format=qcow2 \
    -netdev bridge,id=net0,br=br0 \
    -device virtio-net-pci,netdev=net0 \
    -device usb-ehci,id=ehci \
    -device usb-storage,drive=usbdisk \
    -drive id=usbdisk,if=none,file=/dev/disk/by-id/usb-[YOUR_DEVICE],format=raw \
    -serial file:$HOME/qemuvirt/log/qemu-opensuse-tw-vm.log \
    -display none \
    -daemonize
#    -display default \
#    -device VGA,vgamem_mb=128 \
