#!/bin/sh

sudo qemu-system-x86_64 \
    -name ubuntu-server \
    -pidfile $HOME/qemuvirt/runpid/qemu-ubuntu-server.pid \
    -enable-kvm \
    -cpu host \
    -smp 4,sockets=1,cores=2,threads=2 \
    -m 4096 \
    -drive file=$HOME/qemuvirt/images/ubuntu-server.qcow2,format=qcow2 \
    -netdev bridge,id=net0,br=br0 \
    -device virtio-net-pci,netdev=net0 \
    -device usb-ehci,id=ehci \
    -device usb-storage,drive=usbdisk1 \
    -device usb-storage,drive=usbdisk2 \
    -drive id=usbdisk1,if=none,file=/dev/disk/by-id/usb-[YOUR_DEVICE_1],format=raw \
    -drive id=usbdisk2,if=none,file=/dev/disk/by-id/usb-[YOUR_DEVICE_2],format=raw \
    -serial file:$HOME/qemuvirt/log/qemu-ubuntu-server-vm.log \
    -display none \
    -daemonize

#  -boot d \
#  -cdrom $HOME/qemuvirt/isos/ubuntu-24.04.2-live-server-amd64.iso \
